[tool.poetry]
name = "spendvest"
version = "0.1.0"
description = "spendvest helps mobile money users save money while spending"
authors = ["ong3r1, garfieldotieno"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.1"
dependency-injector = "^4.41.0"
aiohttp = "^3.9.5"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.31"}
aiomysql = "^0.2.0"
python-dotenv = "^1.0.1"
uvicorn = "^0.30.5"
apscheduler = "^3.10.4"

[tool.poetry.scripts]
spendvest = "src.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
