from dataclasses import dataclass
from typing_extensions import TypedDict


@dataclass
class PersonalOnboardingRequestParameters:
    """
    Dataclass for personal onboarding request parameters.

    Attributes:
        merchant_code (`str`): A unique number assigned to an
            organization/merchant registered with ViewTech, through which payment
            is received (can be Paybill or Till number).
        first_name (`str`): The first name of the customer as it appears on the
            identity card or passport
        middle_name (`str`): The middle name of the customer as it appears on
            their identity card of passport
        last_name (`str`): The last name of the customer as it appears on their
            identity card.
        country_code (`str`): This is the country calling code.
        mobile_number (`str`): This is the mobile number identifying merchant
            beneficiary and is required during registration.
        document_number (`str`): This is the number on the identification
            document type.
        document_type (`str`): This is the type of identifying documentation
            for the customer.
        email (`str`): The customer's email.
        callback_url (`str`): This is the link where sasapay will send the data
            about beneficiary status during onboarding process.This data can be
            used by the mechant to update beneficiary status on merchant system.
    """

    merchant_code: str
    first_name: str
    middle_name: str
    last_name: str
    country_code: str
    mobile_number: str
    document_number: str
    document_type: str
    email: str
    callback_url: str


@dataclass
class PersonalOnboardingResponseParameters:
    """
    Dataclass for personal onboarding response parameters.

    Attributes:
        status (`bool`): Status of the request.
        response_code (`str`): This is a numeric status code that indicates the
            status of the response. 0 means success and any other code means an
            error occurred or the request failed.Please refer to the response codes
            table above.
        message (`str`): A description of the response status sent when a
            request is received.
        request_id (`str`): A unique identifier for the registration request
            generated by SasaPay API.
    """

    status: bool
    response_code: str
    message: str
    request_id: str


@dataclass
class PersonalOnboardingConfirmation:
    """
    Dataclass for confirming person onboarding.

    Attributes:
        merchant_code: (`str`): A unique number assigned to an
            organization/merchant registered with ViewTech, through which payment
            is received (can be Paybill or Till number).
        otp (`str`): This is a confirmation code that is sent in response to
            the initial registration POST request when onboarding a new
            beneficiary.
        request_id (`str`): A unique identifier for the registration
    """

    merchant_code: str
    otp: str  # This is sent to the customer registering

    # This is coming from the response parameters of the
    # initial post so it should be in the async event.
    request_id: str


@dataclass
class ConfirmationResponseData(TypedDict):
    """
    Type used to type check the data parameter in a personal onboarding
    confirmation response.

    Attributes:
        merchant_code: (`str`): A unique number assigned to an
            organization/merchant registered with ViewTech, through which payment
            is received (can be Paybill or Till number).
        account_number: (`str`): customer personal account number i.e bank account.
        display_name: (`str`): customer name.
        account_status: (`str`): Status of the created account.
        account_balance: (`int`): customer balance in the wallet.
    """

    merchant_code: str
    account_number: str
    display_name: str
    account_status: str
    account_balance: int


@dataclass
class PersonalOnboardingConfirmationResponseParameters:
    """
    Dataclass for response parameters for confirming personal onboarding.

    Attributes:
        status (`bool`): Status of the request.
        response_code (`str`): This is a numeric status code that indicates the
            status of the response. 0 means success and any other code means an
            error occurred or the request failed.Please refer to the response codes
            table above.
        message (`str`): This is the response message sent by the system when
            the payload is received on the endpoint.
        data (`ConfirmationResponseData`): An object containing the details of
            the registered customer.
    """

    status: bool
    response_code: str
    message: str
    data: ConfirmationResponseData


@dataclass
class RequestPaymentRequestParameters:
    """
    Dataclass for Request Payment request parameters.

    Attributes:
        `merchant_reference (str)`: Unique identifier for this payment request.
        `network_code (str)`: Mobile telecomunications network we are
            requesting the transaction from.
        `mobile_number (str)`: Mobile number from which funds are being
            transfered.
        `receiver_account_number (str)`: Unique number identifying a customer
            whose wallet is to be loaded with funds.
        `amount (str)`: Amount of money being loaded to the customer's wallet.
        `transaction_fee (str)`: This the amount charged as the transaction fee
            for wallet topup.
        `currency_code (str)`: Standardization that defines alpha codes and
            numeric codes for the representation of currencies.
        `merchant_code (str)`: A unique number assigned to an
            organization/merchant registered with ViewTech, through which
            payment is received (can be Paybill or Till number).
        `transaction_description`: A brief description of the purpose of
            topping up the balance.
        `callback_url`: This is the URL where SasaPay will send the results
            after the payment process is initiated.
    """

    merchant_reference: str
    network_code: str
    mobile_number: str
    receiver_account_number: str
    amount: str
    transaction_fee: str
    currency_code: str
    merchant_code: str
    transaction_description: str
    callback_url: str

    def to_dict(self):
        return {
            "merchantReference": self.merchant_reference,
            "networkCode": self.network_code,
            "mobileNumber": self.mobile_number,
            "receiverAccountNumber": self.receiver_account_number,
            "amount": self.amount,
            "transactionFee": self.transaction_fee,
            "currencyCode": self.currency_code,
            "merchantCode": self.merchant_code,
            "transactionDesc": self.transaction_description,
            "callbackUrl": self.callback_url,
        }


@dataclass
class RequestPaymentResponseParameters:
    """
    Dataclass for Request Payment Response Parameters.

    Attributes:
        `status (bool)`: Status of the transaction.
        `response_code (str)`: A code identifying the type of response sent. 0
            means success and any other code means the transaction failed.
        `message (str)`: A description of the response status sent by SasaPay
            API.
        `payment_gateway (str)`: Identifier of the payment gateway we are
            communicating with.
        `checkout_request_id (str)`: A unique identifier for a transaction
            generated by SasaPay API.
        `merchant_reference (str)`: A unique identifier of the transaction
            generated by the Merchant system.
        `customer_message (str)`: These are steps to be followed when you want
            to pay manually from your phone SIM TOOLKIT.
    """

    status: bool
    response_code: str
    message: str
    payment_gateway: str
    checkout_request_id: str
    merchant_reference: str
    customer_message: str

    def to_dict(self):
        return {
            "status": self.status,
            "responseCode": self.response_code,
            "message": self.message,
            "paymentGateway": self.payment_gateway,
            "checkoutRequestID": self.checkout_request_id,
            "merchantReference": self.merchant_reference,
            "customerMessage": self.customer_message,
        }


class RequestPaymentOTPRequestParameters:
    """
    OTP Details to be sent to sasapay to verify transaction.

    Attributes:
        `merchant_code (str)`: A unique number assigned to an
            organization/merchant registered with ViewTech, through which
            payment is received (can be Paybill or Till number)
        `receiver_account_number (str)`: The sasapay wallet id that is
            receiving the funds
        `checkout_request_id (str)`: A unique identifier of the transaction
            request.
        `verification_code (str)`: This is a 6 digit code sent to a mobile
            number making payment. This is the code the authorizes processing
            of the transaction. (OTP)
    """

    merchant_code: str
    receiver_account_number: str
    checkout_request_id: str
    verification_code: str

    def to_dict(self):
        return {
            "merchantCode": self.merchant_code,
            "receiverAccountNumber": self.receiver_account_number,
            "checkoutRequestId": self.checkout_request_id,
            "verificationCode": self.verification_code,
        }


class RequestPaymentOTPResponseParameters:
    """
    Data returned after an OTP request has been sent.

    Attributes:
        `status (bool)`: This is a true or false status that indicates the
            status of the response. true means success and false means an error
            occurred or the request failed.Please refer to the response codes
            table above.
        `response_code (str)`: Code specifying which error occured.
        `message (str)`: Message from the api describing the status of the
            transaction
    """

    status: bool
    response_code: str
    message: str

    def to_dict(self):
        return {
            "status": self.status,
            "responseCode": self.response_code,
            "message": self.message,
        }


@dataclass
class RequestPaymentCallbackResultsParameters:
    """
    Dataclass representing the callback results send by Sasapay after a Request
    Payment request has been completed.

    Attributes:
        `merchant_request_id (str)`: The unique id sent with the transaction
            request from the Merchant system.
        `checkout_request_id (str)`: This is a unique SasaPay transaction ID
            for every payment request. Same value is sent to the customer over
            SMS upon successful processing.
        `payment_request_id (str)`: Unique identifier for a payment request
            transaction.
        `result_code (str)`: The numeric status of the results, sent to the
            callback url
        `result_description (str)`: This is a message from the API that gives
            the status of the request processing and usually maps to a specific
            result code value.
        `source_channel (str)`: Mobile money provider that was part of the
            transaction.
        `transaction_amount (str)`: This is the amount that was transacted. It
            is usually returned under the ResultParameter array.
        `bill_reference_number (str)`: This is a unique SasaPay transaction ID
            for every payment request. Same value is sent to the customer over
            SMS upon successful processing. It is usually returned under the
            ResultParameter array.
        `transaction_date (str)`: This is the date and time that the
            transaction completed SasaPay.
        `customer_mobile (str)`: This mobile number from where the funds are
            requested.
        `transaction_code (str)`: Unique code for this transaction.
        `third_party_transaction_id (str)`: This is the transaction refrence
            from third party systems SasaPay.
    """

    merchant_request_id: str
    checkout_request_id: str
    payment_request_id: str
    result_code: str
    result_description: str
    source_channel: str
    transaction_amount: str
    bill_reference_number: str
    transaction_date: str
    customer_mobile: str
    transaction_code: str
    third_party_transaction_id: str

    def to_dict(self):
        return {
            "MerchantRequestID": self.merchant_request_id,
            "CheckoutRequestID": self.checkout_request_id,
            "PaymentRequestID": self.payment_request_id,
            "ResultCode": self.result_code,
            "ResultDesc": self.result_description,
            "SourceChannel": self.source_channel,
            "TransAmount": self.transaction_amount,
            "BillRefNumber": self.bill_reference_number,
            "TransactionDate": self.transaction_date,
            "CustomerMobile": self.customer_mobile,
            "TransactionCode": self.transaction_code,
            "ThirdPartyTransID": self.third_party_transaction_id,
        }


@dataclass
class TransferFundsRequestParameters:
    pass


@dataclass
class TransferFundsResponseParameters:
    pass


@dataclass
class TransferFundsResultsParameters:
    pass
