"""Initial migration.

Revision ID: c623ca116b9e
Revises:
Create Date: 2024-08-23 18:38:42.236418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c623ca116b9e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("middle_name", sa.String(length=256), nullable=False),
        sa.Column("last_name", sa.String(length=256), nullable=False),
        sa.Column("phone_number", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("whatsapp", sa.String(length=256), nullable=False),
        sa.Column("identifying_document", sa.String(length=256), nullable=False),
        sa.Column("document_number", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer_sessions",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["session_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("savings_percentage", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.String(length=256), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("transaction_amount", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.String(length=256), nullable=False),
        sa.Column("phone_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("wallets")
    op.drop_table("customer_sessions")
    op.drop_table("session_types")
    op.drop_table("customers")
    # ### end Alembic commands ###
