"""Removing wallet data from customers table.

Revision ID: f2af7cba02c9
Revises: c623ca116b9e
Create Date: 2024-08-26 10:34:00.328057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2af7cba02c9'
down_revision: Union[str, None] = 'c623ca116b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'document_number')
    op.drop_column('customers', 'identifying_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('identifying_document', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('customers', sa.Column('document_number', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
